OPENAI_API_KEY =""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT="GettingStartedLangchain"
GROQ_API_KEY="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"
db_user = root
db_password = root
db_host = 127.0.0.1
port= 3306
db_name = finacial